In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/india-rental-house-price/Indian_housing_Mumbai_data.csv
/kaggle/input/india-rental-house-price/Indian_housing_Pune_data.csv
/kaggle/input/india-rental-house-price/Indian_housing_Delhi_data.csv


In [3]:
delhi = pd.read_csv('/kaggle/input/india-rental-house-price/Indian_housing_Delhi_data.csv')
pune = pd.read_csv('/kaggle/input/india-rental-house-price/Indian_housing_Pune_data.csv')
mumbai = pd.read_csv('/kaggle/input/india-rental-house-price/Indian_housing_Mumbai_data.csv')

delhi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   house_type        5000 non-null   object 
 1   house_size        5000 non-null   object 
 2   location          5000 non-null   object 
 3   city              5000 non-null   object 
 4   latitude          5000 non-null   float64
 5   longitude         5000 non-null   float64
 6   price             5000 non-null   int64  
 7   currency          5000 non-null   object 
 8   numBathrooms      4975 non-null   float64
 9   numBalconies      2737 non-null   float64
 10  isNegotiable      179 non-null    object 
 11  priceSqFt         0 non-null      float64
 12  verificationDate  5000 non-null   object 
 13  description       4715 non-null   object 
 14  SecurityDeposit   5000 non-null   object 
 15  Status            5000 non-null   object 
dtypes: float64(5), int64(1), object(10)
memory

In [4]:
pune.info()

mumbai['city'].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3910 entries, 0 to 3909
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   house_type        3910 non-null   object 
 1   house_size        3910 non-null   object 
 2   location          3910 non-null   object 
 3   city              3910 non-null   object 
 4   latitude          3910 non-null   float64
 5   longitude         3910 non-null   float64
 6   price             3910 non-null   int64  
 7   currency          3910 non-null   object 
 8   numBathrooms      3893 non-null   float64
 9   numBalconies      1821 non-null   float64
 10  isNegotiable      526 non-null    object 
 11  priceSqFt         0 non-null      float64
 12  verificationDate  3910 non-null   object 
 13  description       3442 non-null   object 
 14  SecurityDeposit   3910 non-null   object 
 15  Status            3910 non-null   object 
dtypes: float64(5), int64(1), object(10)
memory

array(['Mumbai', 'Hisar'], dtype=object)

In [5]:
mumbai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   house_type        5000 non-null   object 
 1   house_size        5000 non-null   object 
 2   location          5000 non-null   object 
 3   city              5000 non-null   object 
 4   latitude          5000 non-null   float64
 5   longitude         5000 non-null   float64
 6   price             5000 non-null   int64  
 7   currency          5000 non-null   object 
 8   numBathrooms      4986 non-null   float64
 9   numBalconies      733 non-null    float64
 10  isNegotiable      571 non-null    object 
 11  priceSqFt         0 non-null      float64
 12  verificationDate  5000 non-null   object 
 13  description       4922 non-null   object 
 14  SecurityDeposit   5000 non-null   object 
 15  Status            5000 non-null   object 
dtypes: float64(5), int64(1), object(10)
memory

In [6]:
for i in [delhi, mumbai, pune]:
    print(i.head(5))
    print("-"*20)

                 house_type   house_size           location   city   latitude  \
0    1 RK Studio Apartment     400 sq ft            Kalkaji  Delhi  28.545561   
1    1 RK Studio Apartment     400 sq ft  Mansarover Garden  Delhi  28.643259   
2  2 BHK Independent Floor     500 sq ft        Uttam Nagar  Delhi  28.618677   
3  3 BHK Independent House   1,020 sq ft         Model Town  Delhi  28.712898   
4          2 BHK Apartment     810 sq ft   Sector 13 Rohini  Delhi  28.723539   

   longitude  price currency  numBathrooms  numBalconies isNegotiable  \
0  77.254349  22000      INR           1.0           NaN          NaN   
1  77.132828  20000      INR           1.0           NaN          NaN   
2  77.053352   8500      INR           1.0           NaN          NaN   
3  77.180000  48000      INR           3.0           NaN          NaN   
4  77.131424  20000      INR           2.0           NaN          NaN   

   priceSqFt    verificationDate  \
0        NaN    Posted a day ago   
1 

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pan

In [7]:
for i in delhi.columns:
    print(delhi[i].unique())
    print("---"*20)

['1 RK Studio Apartment ' '2 BHK Independent Floor '
 '3 BHK Independent House ' '2 BHK Apartment ' '3 BHK Apartment '
 '3 BHK Independent Floor ' '4 BHK Independent Floor '
 '1 BHK Independent Floor ' '1 BHK Apartment ' '8 BHK Independent Floor '
 '4 BHK Apartment ' '6 BHK Independent Floor ' '2 BHK Independent House '
 '1 BHK Independent House ' '5 BHK Independent Floor '
 '4 BHK Independent House ' '5 BHK Villa ' '5 BHK Independent House '
 '7 BHK Independent Floor ' '8 BHK Independent House '
 '10 BHK Independent House ' '7 BHK Independent House '
 '9 BHK Independent House ' '8 BHK Villa ' '4 BHK Villa '
 '5 BHK Apartment ' '6 BHK penthouse ' '12 BHK Independent House ']
------------------------------------------------------------
['400 sq ft' '500 sq ft' '1,020 sq ft' '810 sq ft' '750 sq ft'
 '1,300 sq ft' '1,200 sq ft' '1,100 sq ft' '2,500 sq ft' '1,162 sq ft'
 '900 sq ft' '1,150 sq ft' '2,000 sq ft' '1,350 sq ft' '1,000 sq ft'
 '2,200 sq ft' '1,800 sq ft' '1,850 sq ft' '1,500 sq

In [8]:
#Merge all 3
merged_data = pd.concat([delhi, mumbai, pune], axis=0)

In [9]:
merged_data.drop(['priceSqFt'],axis=1, inplace=True)

In [10]:
merged_data["numBalconies"] = merged_data["numBalconies"].replace(["null", None], 0).fillna(0)
merged_data["isNegotiable"] = merged_data["isNegotiable"].replace(["Negotiable"], 1).fillna(0)

merged_data['isNegotiable'].unique()

/tmp/ipykernel_37/974413092.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  merged_data["isNegotiable"] = merged_data["isNegotiable"].replace(["Negotiable"], 1).fillna(0)


array([0., 1.])

In [11]:
merged_data["numBathrooms"].unique()

array([ 1.,  3.,  2.,  4.,  8.,  5.,  6.,  7.,  9., nan, 10.])

In [12]:
median_baths = merged_data["numBathrooms"].median()
merged_data["numBathrooms"] = merged_data["numBathrooms"].fillna(median_baths)
merged_data["numBathrooms"].unique()

array([ 1.,  3.,  2.,  4.,  8.,  5.,  6.,  7.,  9., 10.])

In [13]:
import re

# make sure column is str
s = merged_data['house_size'].astype(str)

# 1) Normalize: replace common unicode NBSP and remove commas, unify text
s_clean = (
    s
    .str.replace('\u00A0', ' ', regex=False)   # NBSP -> space
    .str.replace(',', '', regex=False)         # remove commas in numbers
    .str.lower()                               # unify case
    .str.strip()
)

# store cleaned string (optional, for inspection)
merged_data['house_size_clean'] = s_clean

# 2) Primary extraction: only capture numbers that are followed by 'sq ft' (robust to 'sq ft', 'sqft', 'sq. ft' etc.)
merged_data['house_size_num'] = s_clean.str.extract(r'([0-9]+(?:\.[0-9]+)?)\s*(?:sq(?:\.|\s)?ft|square\s?feet|sqft)', flags=re.IGNORECASE)[0]

# 3) Fallback #1: if still missing, try any large number (3+ digits) in the string (likely sqft)
mask_missing = merged_data['house_size_num'].isna()
merged_data.loc[mask_missing, 'house_size_num'] = s_clean[mask_missing].str.extract(r'([0-9]{3,}(?:\.[0-9]+)?)')[0]

# 4) Fallback #2 (optional): if still missing but the value is like '400' (2-3 digits), pick first number
mask_missing = merged_data['house_size_num'].isna()
merged_data.loc[mask_missing, 'house_size_num'] = s_clean[mask_missing].str.extract(r'([0-9]+(?:\.[0-9]+)?)')[0]

# 5) Convert to numeric
merged_data['house_size_num'] = pd.to_numeric(merged_data['house_size_num'], errors='coerce')

# 6) Compute rentPerSqft correctly (price divided by area)
merged_data['rentPerSqft'] = np.where(
    (merged_data['house_size_num'].notna()) & (merged_data['house_size_num'] > 0),
    merged_data['price'] / merged_data['house_size_num'],
    np.nan
)

# 7) Diagnostics: show rows still problematic (very small area or NaN)
problem_rows = merged_data[
    (merged_data['house_size_num'].isna()) |
    (merged_data['house_size_num'] < 50) |   # suspiciously small areas
    (merged_data['rentPerSqft'] > 10000)     # suspiciously high rentPerSqft
][['house_size', 'house_size_clean', 'house_size_num', 'price', 'rentPerSqft']]

print("Number of problematic rows:", len(problem_rows))

if len(problem_rows) == 0:
    display(merged_data[["house_size_num","rentPerSqft", "house_size"]])
else: 
    display(problem_rows.head(50))   # if in notebook; else print(problem_rows.head(50).to_string())


Number of problematic rows: 0


house_size_num  rentPerSqft   house_size
0                400    55.000000    400 sq ft
1                400    50.000000    400 sq ft
2                500    17.000000    500 sq ft
3               1020    47.058824  1,020 sq ft
4                810    24.691358    810 sq ft
...              ...          ...          ...
3905             655    19.083969    655 sq ft
3906             920    17.391304    920 sq ft
3907             650    24.615385    650 sq ft
3908            1200    16.666667  1,200 sq ft
3909             933    18.756699    933 sq ft

[13910 rows x 3 columns]

In [14]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13910 entries, 0 to 3909
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   house_type        13910 non-null  object 
 1   house_size        13910 non-null  object 
 2   location          13910 non-null  object 
 3   city              13910 non-null  object 
 4   latitude          13910 non-null  float64
 5   longitude         13910 non-null  float64
 6   price             13910 non-null  int64  
 7   currency          13910 non-null  object 
 8   numBathrooms      13910 non-null  float64
 9   numBalconies      13910 non-null  float64
 10  isNegotiable      13910 non-null  float64
 11  verificationDate  13910 non-null  object 
 12  description       13079 non-null  object 
 13  SecurityDeposit   13910 non-null  object 
 14  Status            13910 non-null  object 
 15  house_size_clean  13910 non-null  object 
 16  house_size_num    13910 non-null  int64  
 17 

In [17]:
merged_data["house_type_clean"] = merged_data["house_type"].str.strip().str.title()
merged_data["numBHK"] = merged_data["house_type_clean"].str.extract(r"(\d+)\s*Bhk", flags=re.IGNORECASE)
merged_data["numBHK"] = merged_data["numBHK"].fillna(0).astype(int)
def extract_property_type(x):
    x = x.lower()
    if "apartment" in x:
        return "Apartment"
    elif "independent floor" in x:
        return "Independent Floor"
    elif "independent house" in x:
        return "Independent House"
    elif "villa" in x:
        return "Villa"
    elif "penthouse" in x:
        return "Penthouse"
    elif "studio" in x or "rk" in x:
        return "Studio"
    else:
        return "Other"

merged_data["property_type"] = merged_data["house_type_clean"].apply(extract_property_type)
merged_data.drop(columns=["house_type"], inplace=True)

KeyError: 'house_type'

In [18]:
merged_data["verificationDate"].unique()

array(['Posted a day ago', 'Posted 9 days ago', 'Posted 12 days ago',
       'Posted a year ago', 'Posted 2 years ago', 'Posted 3 years ago',
       'Posted 2 months ago', 'Posted a month ago', 'Posted 17 days ago',
       'Posted 13 days ago', 'Posted 15 days ago', 'Posted 19 days ago',
       'Posted 16 days ago', 'Posted 6 days ago', 'Posted 9 months ago',
       'Posted 23 days ago', 'Posted 22 days ago', 'Posted 3 days ago',
       'Posted 4 years ago', 'Posted 11 days ago', 'Posted 10 days ago',
       'Posted 14 days ago', 'Posted 5 months ago', 'Posted 18 days ago',
       'Posted 7 days ago', 'Posted 5 days ago', 'Posted 3 months ago',
       'Posted 4 months ago', 'Posted 20 days ago', 'Posted 4 days ago',
       'Posted 24 days ago', 'Posted 6 hours ago', 'Posted 2 days ago',
       'Posted 21 days ago', 'Posted 25 days ago', 'Posted 16 hours ago',
       'Posted 8 days ago', 'Posted 10 months ago', 'Posted 13 hours ago',
       'Posted 14 hours ago', 'Posted 19 hours ago',


In [19]:
merged_data.to_csv("cleaned_data.csv", index=False)